# $Id: Makefile 100 2011-04-08 15:30:11Z jpuente $

GPRBUILD  = gprbuild
GPRCLEAN = gprclean

all: utilities

utilities: 
	$(GPRBUILD) -Pephemeris_utilities.gpr

clean:
	$(GPRCLEAN) -Pephemeris_utilities.gpr

