name = "create"
description = "Utility for craeting a binary ephemeris file from a JPL ascii file"
version = "0.1.0-dev"

authors = ["Juan A. de la Puente"]
maintainers = ["Juan A. de la Puente <juan.de.la.puente@upm.es>"]
maintainers-logins = ["jpuente"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []

executables = ["create"]

[[ depends-on ]]
ephemeris = "*"

[[ pins ]]
ephemeris = { path = ".."}
